### ISSUE TITLE
Submission for RSE18

### ISSUE THREAD

**Issue by npch** [softwaresaved/code-cite#19]
Should we think about using our newly awesome tools to answer a specific question that we could submit to the RSE conference?

*Deadline for submissions is 30 April*

[Guidance for the submission](http://rse.ac.uk/conf2018/call-talks-posters/) is:

> Topic and abstract
>
> The abstract should be relatively brief and attention-grabbing rather than an exhaustive explanation of the material you wish to cover.
> Both the topic and the abstract will be published on the conference website.
>
> Audience
> Would your target audience be required to have any prerequisite skills/background knowledge e.g. knowledge of a particular language?
>
> Outcomes
> How will your attendees benefit from the talk/poster?  What do you expect them to gain/learn?

**Comment by npch** [comment]
My suggestion is something that would provoke discussion like: “Which domain has the most repeatable papers? An empirical comparison using code-cite”

**Comment by npch** [comment]
@npscience said: 

> That sounds like a great idea. My preference would be to complete the work on “github.com” (do they resolve, license, etc) and maybe extend to other repositories if time to see which communities use which platform? We could use the journal titles and/or article keywords in the getpapers JSON output to identify communities?

**Comment by npch** [comment]
@longr said:

> I will hopefully get some time in the week beginning the 9th to sit down again with the code and look at it.   So any suggestions of what you want out of github, (tag as: Required, Ideal, Desirable) if you can get them to me be before the 9th I should be able to get them coded.

**Comment by npch** [comment]
@shoaibsufi said:

> I am interested in taking part - not sure what I could do just now - but please keep me in the loop

**Comment by andreww** [comment]
I'm happy to contribute to this, but I won't be able to make it to Birmingham in September. I think this abstract should focus on questions we can answer from a one-off search of EuroPMC focussing on links to github.com. Other repositories of papers, other software repositories, or measuring changes in software repositories with time, all feel like a stretch goals (but we should build things with these in mind).

If we want to compare practices across disciplines we should keep in mind how (in)complete EuroPMC will be. If I understand it correctly this means we would be better comparing disciplines belonging to the bio-medical sciences and not, say, comparing history and geology.  To do any comparison we'll need to extract a discipline (or disciplines) from the papers (or journals) and pass these along with the doi, publication date, and list of github urls. This will give us a big list of software repositories (each with some quality estimate) that we can analyse by the discipline that uses the software. We can also pull out any tags from the github repos, but my impression is that this won't tell us a lot. (I'll turn these ideas into additional issues.)

**Comment by npch** [comment]
So I did [some analysis](https://github.com/softwaresaved/code-cite/blob/abd6ad878e993cf1ff0e290ede9232918cbe135a/notebooks/IsSoftwareUpdated.ipynb) on whether software repositories referenced in papers are updated after the publication of the paper.

This is ran on the "very small" EUPMC dataset, but you can see that about half don't update, there's a whole lot with a small update frequency, then a few outliers (mrdoob/three.js and pandas-dev/pandas - both very popular generic tools).

What I need to be able to do is to differentiate between the software created by the author for the purposes of this paper, and the software used by the author in the course of doing the work represented by the paper. I've opened #24 to address this.

**Comment by npch** [comment]
This was submitted and presented.
